version: "3"
services: 
  job:
    image: xuxueli/xxl-job-admin:2.3.0
    ports: 
    - "8080:8080"
    volumes: 
    - "./tmp:/data/applogs"
    - "./application.properties:/application.properties"
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3316:3306
    command:  --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: demoapp
      TZ: Asia/Shanghai
 